# APPLICATION
spring.application.name=escolaweb

# SERVER
server.port=${SERVER_PORT}

# DATASOURCE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# LOGGING SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# THYMELEAF
spring.thymeleaf.cache=false


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


# DEVTOOLS
spring.devtools.restart.enabled=true

# ERROR
server.error.include-message=always
server.error.include-binding-errors=always